### PR TITLE
Update of build system

### PR DESCRIPTION
**Pull request by rlalik**
In the other PR I made to many changes at once. In this PR I started from scratch and made only minimal changes to the build system. But some changes in the core macros of DABC were required.

The usual way of copying headers to build directory still works like before so there should be no compatibility issues, but now it is also possible to make out-of-build installations with `make install`.

I am still testing this against my project which use dabc so let me take a couple of days until final version is comited.

Main changes:
* small modernization to use target definitions instead of variables for targets (include paths, etc)
* cmake formatter to keep syntax consistent
* each plugin and other module uses explicite list of files instead of GLOBs, as GLOBs cannot detect changes in the files on disk (like new file appeared), and are highly discouraged in this context

### CODE REVIEW

**Comment by linev** [comment]
@rlalik 
It looks much better now!

Install is not yet perfect, but before it was not working at all.
With the time we could improve it.

I will try to analyze your PR in details now

**Comment by rlalik** [comment]
Let me know the issues with install and I look on them.

**Comment by linev** [comment]
> Let me know the issues with install and I look on them.

Main issue - cmake install command works for global dirs like `/usr` or `/usr/local`.
In case when installation should be done in directory like `/cvmfs/eel.gsi.de/debian10-x86_64/dabc/` (GSI CVMFS), 
one should better reproduce file structure as in build directory and provide proper `dabclogin` script

**Comment by rlalik** [comment]
You would need to specify how the tree should looks.

I assumed that since until now the dabc was not properly installable noone used this so I can make proper linux tree as the default. There is however cmake variable `DABC_LEGACY_INSTALL` which will install plugins dir not in e.g. `$ROOT/share/dabc` like in Linux tree, but in `$ROOT`, next to `lib64` and `include` and so on, and this I think reflects the GSi install structure. You can make more specifications and I can apply them to this flag. We can rename it from LEGACY to something else like `DABC_GSI_INSTALL` or so.

**Comment by rlalik** [comment]
I think with these changes you should be happy about build/install linux/legacy modes. If there are some issues, please point them directly that I can handle them.

**Comment by linev** [comment]
We will test PR one several other platforms, but for me it looks ok now.

**Comment by linev** [comment]
@rlalik 

I found problem when ROOT is not configured - then I get error like:

```
CMake Error at cmake/modules/DabcMacros.cmake:217 (add_custom_command):
  No TARGET 'DabcRoot' has been created in this directory.
Call Stack (most recent call first):
  cmake/modules/DabcMacros.cmake:187 (dabc_install_plugin_data_source)
  plugins/root/CMakeLists.txt:32 (dabc_install_plugin_data)
```

**Comment by linev** [comment]
I am not sure that `DABC_INSTALL_PLUGIN_DATA_SOURCE` is correct.
It uses target (which may not exists) and variable `tgt` is not used

**Comment by linev** [comment]
I could move jsroot to other location to avoid logical problem. But in any case `DABC_INSTALL_PLUGIN_DATA_SOURCE` should be checked

**Comment by linev** [comment]
@rlalik 
You changes ROOT plugin, but `root/js` directory should be copied also when ROOT plugin is not compiled.
JSROOT is used by `HttpServer` in DABC also without ROOT
One need extra rule for copying directory `plugins/root/js`

**Comment by rlalik** [comment]
Ok, I was testing the build system and found out an issue with cmake and http module which uses OpenSSL.

First, probably one needs to bump required cmake version. `3.9` is hardy available on recent Ubuntues (is there reason for this minimal cmake version?), in GSI debian8 does not provides cmake (does it?), so it is anyway incompatible, debian10 uses `3.13.4`. So I would suggest to use 3.13 as minimal, unless there is a reason for lower version of `3.9`.

The problem... OpenSSL starting from 3.0 has different way to define its version and only cmake-3.13.3 can handle it (https://github.com/Kitware/CMake/blob/e647949539f4704a00eddac2357d59ceeb8bc0ca/Modules/FindOpenSSL.cmake#L418-L427).

So using cmake-3.13 will not make it working properly and cmake will have error due to missing `OPENSSL_VERSION`. Since your build allows for OpenSSL version 3.0 there are two straight ways, and neither works:
1. Bump required cmake version to 3.17.3 (not possible at debian10)
2. Allow only OpenSSL 1.0 and 1.1 (what about 3.0, an 3.1...)

The third options is to write custom core to find this version, which currently I will do. Just to let you know what is going to happen.

**Comment by rlalik** [comment]
Seems that issues are OK. I also made a github actions to test diferent build types and configurations. Currently I test:
1. Build system, with following combinations of compilers and cmake:
    `[ gcc-10, gcc-12, clang-11, clang-14 ] x [ cmake-3.13, cmake-latest ]`
3. Build configurations:
 * legacy mode
 * modern mode
 * no ROOT mode

I can add other combinations of modes if you wish. Before you accept PR I must made one change on the actions so please let me know just before the merge that I can commit one more.

**Comment by linev** [comment]
Only now I saw that all tests building static libraries instead of shared one.
Like `libDabcCoreTest.a` instead of `libDabcCoreTest.so`.
Also this library should not appear in main `lib` directory in build directory - it should stay in its own dir.

**Comment by rlalik** [comment]
What is exactly in the `applications`? Are those test codes? Should they be executed for testing? Or they just should pass compilation and this is the test? Are those examples of usage intended to be extended by a user?

If they are tests, perhaps should be called then tests and run as tests. If they are examples, I would call the examples. The name `applications` suggest that they should be a part of binary distribution.

**Comment by linev** [comment]
In `applications` folder are DABC-based applications. It is not part of DABC and should not appear in the install.
These applications should be build during normal compilation - but libs and executables should not appear in default build dirs. In principle, one could use some of these apps for CI testing - but this can be tried later.

Can you make building of shared libraries for these applications?
It is crucial while DABC uses shared libraries to load and run these tests.

**Comment by rlalik** [comment]
Can I put them under build into `apps/bin` and `apps/lib`? That will put everything in one place, otherwise they will be sitting under `applications/xxx/` with other cmake 'junk files'.

**Comment by linev** [comment]
> Can I put them under build into apps/bin and apps/lib

I prefer to have all these tests separately from each other.
Therefore solution with `applications/xxx/` is better

**Review by linev — APPROVED** [review]
Grate! I merging PR!

**Comment by rlalik** [comment]
Perfect :-)

**Comment by linev** [comment]
Thanks Rafal!

I just create next PR #6 to fix problem with JSROOT installation and see how CI works:

**Pull request merged**
