### PR TITLE
Major rework of cmake build files to modernize cmake scripts

### PR DESCRIPTION
**Pull request by rlalik**
Hi, here is the proposition of the cmake build system updates. It significantly modernises the build ystem to use modern cmake features (cmake-3.0 and higher).

Main changes include:
* namespaced targets `dabc::`
* target properties (link dirc, lib dirs, compiler flags) instead of variables
* using explicit file names instead of `GLOB`s
* actual installation of libs and public headers
* inherit compilation options (c++ standard) directly from ROOT
* better handling some variables like dabc version - use built in `PROJECT_VERSION` variable instead of extra string.
* many other small improvements

To format cmake files I used `cmake-format`, there is config file which handles dabc macros.

I checked whether everything compiles and links properly but real usage test are required from the experts side.

I also added CI test to check compilation on each push/pr.

### CODE REVIEW

**Comment by linev** [comment]
Wow! 
Grate job!

Did you use some other project as template?

I need some time to review such fundamental PR

**Comment by rlalik** [comment]
No, I am just pretty effective with cmake, I use it as my main build system since like 10 years or more, and I just know it. Almost all my project on github use cmake :-)

**Comment by linev** [comment]
Hi Rafal,

First of all - Joern (@jamusch) currently adjusting cmake for LTSM plugin. After his changes PR need to be adjusted. 

Beside it, there are several points I found:
1. Major point - neither DABC nor any plugin can be compiled without ROOT login. But ROOT should be optional component. If it there - use its configuration like c++ standard, if not - use DABC defaults (c++11).  
2. None of includes are copied into build directory. But they are necessary to be able build any external code. It was a task of `DABC_INSTALL_HEADERS` macro.
3. verbs plugin is not compiling because of missing `dabc_install_headers` command. 
4. ROOT plugin is not compiled - missing `ROOT::Tree` in list of dependencies (simple fix)

Using namespaces is good idea.
Not able to test yet, but also automatic compilation tests by each commit is grate.

Completely missing up to now - install configuration for DABC with independent destination dir. 
But this can be resolved once we fix all issues and merge this PR into master.

**Comment by linev** [comment]
@rlalik Can you rebase PR now after Joern changes and resolve main issue with ROOT and installed headers?

**Comment by rlalik** [comment]
Answering to first message.
1. isn't it a risky game? If it is need why not making it required? it is like introducing loophole which can cause troubles.
2. I know that ROOT uses `move_headers` but this is not a good practice. You do not want to rely on the build directory, which is fragile due to possible recompiles, as an reference for external projects. You should rely on the installed files: `make install` which make a released version, and any changes to the current build will not affect external which should depend on stable install files. When new version is ready, install'em again. The current cmake build system installs all headers during installation. Are you sure about requested behaviour?
3. Ok, fixed, removed unnecessary `install_headers` command in the next commit.
4. Ok, should be fixed in the commit

**Comment by linev** [comment]
1. ROOT is optional for DABC. It was never used in production, several components were introduced just as prove of principles. 
2. In most cases we use build directory as is. Actually install is not yet working for DABC at all

**Comment by linev** [comment]
1. Many libraries and all executables are not installed during installation step
2. Installation step distributes libraries, binaries and other files on different sub-folders like `/usr/bin` , `/usr/lib64` and so on. Such kind of installation is not desired and not supported by DABC. All files should be collected in one main subdirectory (aka `$DABCSYS`) and used from there. This is also main reason why build directory can be used as `$DABCSYS` - after build step it contains all necessary files.
3. None of includes, xml, html or JavaScript files copied into build directory.

Can you adjust your PR?

**Comment by rlalik** [comment]
The missing fiels was fixed. The issue of distributing files can be easily solved with:
```bash
export DABCDIR=...
cmake .. -DCMAKE_INSTALL_PREFIX=$DABCDIR
```
and all files will go to `$DABCDIR/bin`, `$DABCDIR/lib64`, `$DABCDIR/shared/plugins`

And I made tests with this, I moved all applications outside build tree, I made dabc installation and each app was build manually with
```bash
cmake .. -DDABC_DIR=$DABCDIR/lib64/cmake/DABC/
```
and all compiled correct.

I do not know whether the paths to plugins are hardcoded somewhere in the binaries or pregenerated config files, if yes they should be properly handled. I don't know all the quirks of the DABC, I was like improvising for the build system based on my experience and what I found in the code. If there are some issues I can fix them but this is really better way to handle projects than leaving everything in build dir. This is how you should do it with proper and modern cmake.

**Comment by linev** [comment]
> `$DABCDIR/shared/plugins`

Can it be simply `$DABCDIR/plugins`?
Some HTML/JS/image files are searched by DABC in `plugins` directory relative to `$DABCSYS` - without `shared` in between.

> I do not know whether the paths to plugins are hardcoded somewhere 

All paths are relative to `$DABCSYS`. If DABCSYS specified - file structure with subfolders should correspond 
to files structure in source directory.

Later I could extend DABC functionality that it search for plugins folder is '/usr/share/DABC/` when no DABCSYS is set.
This will allow support of DABC installation with default prefix

**Comment by rlalik** [comment]
The `$DABCDIR/shared/plugins` comes from using https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html for making install paths. This assures that if some user decides to install it into `/usr` or `/usr/local` (and is always allowed for that), the system paths will not be bloated. The system provides `/usr/share/<project>` location for a such purpose.

So changing this creates risks of bloating system locations. Could the paths be easily updated in the code? I guess so, then this would be better way to go. I can do what you suggest, it is certainly possible, though not recommended.

**Comment by linev** [comment]
> Could the paths be easily updated in the code? 

It is rather about backward compatibility. 
Old `Makefile` building DABC in source directory and using all extra files directly from source.
Changing this logic will break all old installations.

**Comment by linev** [comment]
@rlalik Should I try to adjust your PR?

**Comment by rlalik** [comment]
Sure, go ahead.

**Comment by linev** [comment]
@rlalik 
It still does not work. I get many warnings like:
```
CMake Warning (dev) at cmake/modules/DabcMacros.cmake:71 (install):
  Target DabcBase has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
Call Stack (most recent call first):
  base/CMakeLists.txt:1 (dabc_link_library)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
And DABC does not compiled without ROOT giving failure:
```
CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindROOT.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ROOT", but
  CMake did not find one.

  Could not find a package configuration file provided by "ROOT" with any of
  the following names:

    ROOTConfig.cmake
    root-config.cmake

  Add the installation prefix of "ROOT" to CMAKE_PREFIX_PATH or set
  "ROOT_DIR" to a directory containing one of the above files.  If "ROOT"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/linev/build/abc/DABCConfig.cmake:3 (find_dependency)
  CMakeLists.txt:3 (find_package)
```
If compiled with ROOT, during install step .pcm and .rootmap files are not installed.

**Comment by rlalik** [comment]
I'll handle this issues on Monday.

**Comment by linev** [comment]
I really like a way that build directory can be used as is for running DABC.
This is how all our other cmake are working: ROOT, Go4, stream. 

And install can be used to deploy DABC in two different ways:
1. In default prefix 
2. In dedicated subfolder where directory structure corresponds source and build directory

Should we try to split your PR on several smaller stages?
Otherwise it will be difficult to converge - you removed a lot of useful functions, which I want to have.

**Comment by rlalik** [comment]
This commit addresses the warning issues about `PUBLIC_HEADERS`.

**Comment by rlalik** [comment]
And this fixes the root dependency. Now all should compile and pass tests. I'll work on in-build mode, though I still consider it a bad design.

**Comment by linev** [comment]
Can be closed in favor of #5

**Pull request closed without merging**
